// Generated by CoffeeScript 1.8.0

/*
	Copyright (c) 2011-2014, David Pearson
	All rights reserved.

	Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

	Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
	Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
Data;
var Data, parseASCIIArray, parseASCIIDictionary, parseASCIIPlist, startsWithIgnoringSpace;

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  Data = require("./data");
}

startsWithIgnoringSpace = function(str, what) {
  var start;
  start = str.replace(/\s/g, "").substring(0, what.length);
  return start === what;
};

parseASCIIPlist = function(ascii) {
  return parseASCIIDictionary(ascii);
};

parseASCIIDictionary = function(item) {
  var comp, countOpen, dict, i, j, k, key, keys, l, n, sp, txt, vals, workingQuotes;
  i = 0;
  n = 0;
  comp = 0;
  countOpen = 0;
  workingQuotes = false;
  txt = "";
  keys = [];
  vals = [];
  sp = item.split("{");
  if (sp.length === 1) {
    return null;
  }
  k = 1;
  while (k < sp.length) {
    txt += "{" + sp[k];
    k++;
  }
  txt = txt.substring(1, txt.length);
  item = "";
  sp = txt.split("}");
  if (sp.length === 1) {
    return null;
  }
  l = 0;
  while (l < sp.length - 1) {
    item += sp[l] + "}";
    l++;
  }
  item = item.substring(0, item.length - 1);
  while (item[i] != null) {
    if (keys[n] == null) {
      keys[n] = "";
    }
    if (!vals[n]) {
      vals[n] = "";
    }
    if (comp === 0) {
      while ((item[i] != null) && item[i] !== "=") {
        keys[n] += item[i];
        i++;
      }
      comp = 1;
      i++;
    } else if (comp === 1) {
      while ((item[i] != null) && (item[i] !== ";" || countOpen !== 0)) {
        vals[n] += item[i];
        if (item[i] === "\"" && i - 1 >= 0 && item[i - 1] !== "\\") {
          workingQuotes = !workingQuotes;
        }
        if (!workingQuotes && (item[i] === "{" || item[i] === "(")) {
          countOpen++;
        }
        if (!workingQuotes && (item[i] === "}" || item[i] === ")")) {
          countOpen--;
        }
        i++;
      }
      comp = 0;
      i++;
      n++;
    }
  }
  if (keys.length !== vals.length) {
    return null;
  }
  dict = {};
  j = 0;
  while (j < keys.length) {
    key = keys[j].replace(/\s/g, "");
    if (key === "") {
      continue;
    }
    if (startsWithIgnoringSpace(vals[j], "{")) {
      dict[key] = parseASCIIDictionary(vals[j]);
    } else if (startsWithIgnoringSpace(vals[j], "(")) {
      dict[key] = parseASCIIArray(vals[j]);
    } else {
      dict[key] = vals[j];
    }
    j++;
  }
  return dict;
};

parseASCIIArray = function(item) {
  var ar, countOpen, i, j, k, l, n, sp, txt, vals, workingQuotes;
  i = 0;
  n = 0;
  countOpen = 0;
  workingQuotes = false;
  txt = "";
  vals = [];
  sp = item.split("(");
  if (sp.length === 1) {
    return null;
  }
  k = 1;
  while (k < sp.length) {
    txt += "(" + sp[k];
    k++;
  }
  txt = txt.substring(1, txt.length);
  item = "";
  sp = txt.split(")");
  if (sp.length === 1) {
    return null;
  }
  l = 0;
  while (l < sp.length - 1) {
    item += sp[l] + ")";
    l++;
  }
  item = item.substring(0, item.length - 1);
  while (item[i] != null) {
    if (vals[n] == null) {
      vals[n] = "";
    }
    while ((item[i] != null) && (item[i] !== ";" || countOpen !== 0)) {
      vals[n] += item[i];
      if (item[i] === "\"" && i - 1 >= 0 && item[i - 1] !== "\\") {
        workingQuotes = !workingQuotes;
      }
      if (!workingQuotes && (item[i] === "{" || item[i] === "(")) {
        countOpen++;
      }
      if (!workingQuotes && (item[i] === "}" || item[i] === ")")) {
        countOpen--;
      }
      i++;
    }
    i++;
    n++;
  }
  ar = [];
  j = 0;
  while (j < vals.length) {
    if (startsWithIgnoringSpace(vals[j], "{")) {
      ar.push(parseASCIIDictionary(vals[j]));
    } else if (startsWithIgnoringSpace(vals[j], "(")) {
      ar.push(parseASCIIArray(vals[j]));
    } else {
      ar.push(vals[j]);
    }
    j++;
  }
  return ar;
};

Object.prototype.toPlistASCII = function() {
  var i, ret, _ref;
  ret = "{ ";
  for (i in this) {
    if ((((_ref = this[i]) != null ? _ref.toPlistASCII : void 0) != null) && typeof this[i] !== "function") {
      ret += i + " = " + this[i].toPlistASCII() + "; ";
    }
  }
  return ret += "}";
};

Object.prototype.exportASCII = function() {
  return this.toPlistASCII();
};

String.prototype.toPlistASCII = function() {
  return "\"" + this.replace(/\"/g, "\\\"") + "\"";
};

Number.prototype.toPlistASCII = function() {
  return this.toString().toPlistASCII();
};

Date.prototype.toPlistASCII = function() {
  return this.toString().toPlistASCII();
};

Array.prototype.toPlistASCII = function() {
  var i, ret, _ref;
  ret = "( ";
  i = 0;
  while (i < this.length) {
    if (((_ref = this[1]) != null ? _ref.toPlistASCII : void 0) != null) {
      ret += this[i].toPlistASCII() + ", ";
    }
    i++;
  }
  return ret += ")";
};

Boolean.prototype.toPlistASCII = function() {
  return this.toString().toPlistASCII();
};

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  exports.parseASCIIPlist = parseASCIIPlist;
}
