// Generated by CoffeeScript 1.7.1

/*
	Copyright (c) 2011-2014, David Pearson
	All rights reserved.

	Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

	Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
	Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
DOMParser;
var DOMParser, Data, objectForChildNode, parseXMLArray, parseXMLDictionary, parseXMLPlist;

if (typeof DOMParser === "undefined" || DOMParser === null) {
  DOMParser = require("xmldom").DOMParser;
}

Data;

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  Data = require("./data");
}

parseXMLPlist = function(xml) {
  var node;
  if (typeof xml === "string") {
    xml = new DOMParser().parseFromString(xml, "text/xml");
  }
  node = xml.getElementsByTagName("dict")[0];
  return parseXMLDictionary(node);
};

objectForChildNode = function(childNode) {
  var date, dt, hms, obj, str, ymd;
  obj = null;
  switch (childNode.tagName) {
    case "string":
      obj = childNode.childNodes[0].nodeValue;
      break;
    case "integer":
      obj = parseInt(childNode.childNodes[0].nodeValue);
      break;
    case "real":
      obj = parseFloat(childNode.childNodes[0].nodeValue);
      break;
    case "true":
      obj = true;
      break;
    case "false":
      obj = false;
      break;
    case "date":
      str = childNode.childNodes[0].nodeValue;
      dt = str.split("T");
      ymd = dt[0].split("-");
      hms = dt[1].split("Z")[0].split(":");
      date = new Date();
      date.setUTCFullYear(ymd[0]);
      date.setUTCMonth(ymd[1] - 1);
      date.setUTCDate(ymd[2]);
      date.setUTCHours(hms[0]);
      date.setUTCMinutes(hms[1]);
      date.setUTCSeconds(hms[2]);
      obj = date;
      break;
    case "data":
      obj = new Data();
      if (childNode.childNodes.length > 0) {
        obj.value = childNode.childNodes[0].nodeValue;
      }
      break;
    case "dict":
      obj = parseXMLDictionary(childNode);
      break;
    case "array":
      obj = parseXMLArray(childNode);
      break;
    default:
      obj = null;
  }
  return obj;
};

parseXMLDictionary = function(node) {
  var childNode, children, dict, i, key;
  children = node.childNodes;
  i = 0;
  dict = {};
  key = null;
  childNode = null;
  while (children[i] != null) {
    if (children[i].tagName === "key") {
      key = children[i].childNodes[0].nodeValue;
      childNode = children[i + 2];
      dict[key] = objectForChildNode(childNode);
    }
    i++;
  }
  return dict;
};

parseXMLArray = function(node) {
  var ar, childNode, children, i, key, obj;
  children = node.childNodes;
  i = 1;
  ar = [];
  key = null;
  childNode = null;
  while (children[i] != null) {
    if (children[i].tagName != null) {
      obj = objectForChildNode(children[i]);
      if (obj != null) {
        ar.push(obj);
      }
    }
    i++;
  }
  return ar;
};

Object.prototype.toPlistXML = function() {
  var i, item, key, ret, xml, _ref;
  ret = "<dict>\n";
  for (i in this) {
    if ((((_ref = this[i]) != null ? _ref.toPlistXML : void 0) != null) && typeof this[i] !== "function") {
      key = "<key>" + i + "</key>";
      xml = this[i].toPlistXML();
      if (xml.indexOf("<dict>") >= 0 || xml.indexOf("<array>") >= 0) {
        item = xml;
        item = item.replace(/\n/g, "\n\t");
        ret += "\t" + key + "\n\t" + item + "\n";
        item = "";
      } else {
        ret += "\t" + key + "\n\t" + xml + "\n";
      }
    }
  }
  return ret += "</dict>";
};

Object.prototype.exportXML = function() {
  return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n" + this.toPlistXML() + "\n</plist>";
};

String.prototype.toPlistXML = function() {
  return "<string>" + this + "</string>";
};

Number.prototype.toPlistXML = function() {
  if (this.toFixed() === this) {
    return "<integer>" + this.toString() + "</integer>";
  } else {
    return "<real>" + this.toString() + "</real>";
  }
};

Date.prototype.toPlistXML = function() {
  return "<date>" + this.getUTCFullYear() + "-" + (this.getUTCMonth() + 1) + "-" + this.getUTCDate() + "T" + this.getUTCHours() + ":" + this.getUTCMinutes() + ":" + this.getUTCSeconds() + "Z</date>";
};

Array.prototype.toPlistXML = function() {
  var i, item, ret, xml, _ref;
  ret = "<array>\n";
  i = 0;
  while (i < this.length) {
    if (((_ref = this[1]) != null ? _ref.toPlistXML : void 0) != null) {
      xml = this[i].toPlistXML();
      if (xml.indexOf("<dict>") >= 0 || xml.indexOf("<array>") >= 0) {
        item = xml;
        item = item.replace(/\n/g, "\n\t");
        ret += "\t" + item + "\n";
        item = "";
      } else {
        ret += "\t" + xml + "\n";
      }
    }
    i++;
  }
  return ret += "</array>";
};

Boolean.prototype.toPlistXML = function() {
  return "<" + this.toString() + "/>";
};

Data.prototype.toPlistXML = function() {
  return "<data>" + this.value + "</data>";
};

if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
  exports.parseXMLPlist = parseXMLPlist;
}
